appName: shipping
replicaCount: 1

image: 
  repository: 608320470413.dkr.ecr.us-east-1.amazonaws.com/shipping
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: shipping

service:
  type: ClusterIp 
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 1024Mi

